services:
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml


  grafana:
    image: grafana/grafana:10.4.5
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana


  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cc_project
      POSTGRES_USER: sofijadjukic
      POSTGRES_PASSWORD: sofijasofija
    ports:
      - "5432:5432"
    volumes:
      - bookdb:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command: start-dev  --hostname=http://keycloak:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data


  app:
    build:
      context: .
      dockerfile: book-service/Dockerfile
    depends_on:
      - db
      - keycloak
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cc_project
      SPRING_DATASOURCE_USERNAME: sofijadjukic
      SPRING_DATASOURCE_PASSWORD: sofijasofija
      SERVER_PORT: 8084
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/hibook
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,mappings,metrics,prometheus





  user:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    depends_on:
      - db
      - keycloak

    ports:
      - "8083:8083"
    environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cc_project
       SPRING_DATASOURCE_USERNAME: sofijadjukic
       SPRING_DATASOURCE_PASSWORD: sofijasofija
       SERVER_PORT: 8083
       SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/hibook
       MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,mappings,metrics,prometheus
       SERVER_ERROR_INCLUDE_MESSAGE: always
       SERVER_ERROR_INCLUDE_EXCEPTION: "true"
       SERVER_ERROR_INCLUDE_STACKTRACE: always
       LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: DEBUG
       LOGGING_LEVEL_ORG_HIBERNATE_SQL: DEBUG



volumes:
  bookdb:
  keycloak_data:
  grafana_data:

