services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cc_project
      POSTGRES_USER: sofijadjukic
      POSTGRES_PASSWORD: sofijasofija
    ports:
      - "5432:5432"
    volumes:
      - bookdb:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cc_project
      SPRING_DATASOURCE_USERNAME: sofijadjukic
      SPRING_DATASOURCE_PASSWORD: sofijasofija

volumes:
  bookdb:
