services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cc_project
      POSTGRES_USER: sofijadjukic
      POSTGRES_PASSWORD: sofijasofija
    ports:
      - "5432:5432"
    volumes:
      - bookdb:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: book-service/Dockerfile
    depends_on:
      - db
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cc_project
      SPRING_DATASOURCE_USERNAME: sofijadjukic
      SPRING_DATASOURCE_PASSWORD: sofijasofija
      SERVER_PORT: 8084

volumes:
  bookdb:
