global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "book"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["app:8084"]

  - job_name: "user"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["user:8083"]

