apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: hibook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudcomp
  template:
    metadata:
      labels:
        app: cloudcomp
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z db 5432; do echo waiting for db; sleep 2; done;"]
      containers:
        - name: cloudcomp
          image: cloudcomp-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/cc_project
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
